export const glGroupDefaults: string[] = [
  'Capital Account',
  'Reserves & Surplus',
  'Loans (Liability)',
  'Current Liabilities',
  'Fixed Assets',
  'Current Assets',
  'Misc. Expenses (ASSET)',
  'Branch / Divisions',
  'Sales Accounts',
  'Direct Incomes',
  'Indirect Incomes',
  'Purchase Accounts',
  'Direct Expenses',
  'Bank OCC Account / OD Account / CC Account',
  'Secured Loans',
  'Unsecured Loans',
  'Duties & Taxes',
  'Provisions',
  'Sundry Creditors',
  'Bank Accounts',
  'Cash-in-Hand',
  'Deposits (Asset)',
  'Loans & Advances (Asset)',
  'Stock-in-Hand',
  'Sundry Debtors',
  'Investments',
]
