import type { AdminField, AdminResource } from './types'

const text = (name: string, label: string, required = false): AdminField => ({
	name,
	label,
	kind: 'text',
	required,
})

const longText = (name: string, label: string): AdminField => ({
	name,
	label,
	kind: 'text',
	multiline: true,
})

const number = (name: string, label: string, required = false): AdminField => ({
	name,
	label,
	kind: 'number',
	required,
})

const date = (name: string, label: string): AdminField => ({
	name,
	label,
	kind: 'date',
})

const boolean = (name: string, label: string): AdminField => ({
	name,
	label,
	kind: 'boolean',
})

export const adminResources: AdminResource[] = [
	{
		key: 'user-enquiry',
		label: 'User Enquiry',
		endpoint: '/api/v1/user-enquiries/',
		fields: [
			text('candidate_name', 'Candidate name', true),
			text('father_name', 'Father name'),
			date('date_of_birth', 'Date of birth'),
			text('blood_group', 'Blood group'),
			text('marital_status', 'Marital status'),
			longText('address', 'Address'),
			text('phone', 'Phone'),
			text('pan', 'PAN'),
			text('aadhaar', 'Aadhaar'),
			text('passport_no', 'Passport number'),
			text('personal_email', 'Personal email'),
			text('emergency_phone_1', 'Emergency phone 1'),
			text('emergency_phone_2', 'Emergency phone 2'),
			text('mother_tongue', 'Mother tongue'),
			text('other_languages_known', 'Other languages known'),
			text('religion', 'Religion'),
			text('nationality', 'Nationality'),
			text('highest_qualification', 'Highest qualification'),
			text('year_of_pass', 'Year of pass'),
			text('highest_qualification_document', 'Highest qualification document'),
			text('year_of_pass_document', 'Year of pass document'),
			text('current_employer', 'Current employer'),
			text('current_position', 'Current position'),
			text('department', 'Department'),
			text('working_period', 'Working period'),
			longText('role_responsibilities', 'Role responsibilities'),
			text('current_ctc', 'Current CTC'),
			text('employer_documents', 'Employer documents'),
			text('previous_employer_name', 'Previous employer name'),
			text('previous_employer_position', 'Previous employer position'),
			text('previous_employer_department', 'Previous employer department'),
			text('previous_employer_working_period', 'Previous employer working period'),
			longText('previous_employer_role', 'Previous employer role'),
			text('previous_employer_ctc', 'Previous employer CTC'),
			text('previous_employer_documents', 'Previous employer documents'),
			boolean('is_active', 'Active'),
		],
	},

	{
		key: 'attendance',
		label: 'Attendance',
		endpoint: '/api/v1/attendance/',
		fields: [
			number('user_id', 'User ID', true),
			number('cl', 'CL'),
			number('el', 'EL'),
			number('pl', 'PL'),
			number('lop', 'LOP'),
			number('nh', 'NH'),
			number('sundays', 'Sundays'),
			number('other_paid_days', 'Other paid days'),
			number('net_present_days', 'Net present days', true),
		],
	},

	{
		key: 'employment-details',
		label: 'Employment Details',
		endpoint: '/api/v1/employment/',
		fields: [
			number('user_id', 'User ID', true),
			text('employee_code', 'Employee code'),
			text('designation', 'Designation'),
			text('department', 'Department'),
			text('immediate_reporting_head', 'Immediate reporting head'),
			text('department_head', 'Department head'),
			text('location', 'Location'),
			text('epf_uan', 'EPF UAN'),
			text('esi', 'ESI'),
			text('health_insurance', 'Health insurance'),
			date('health_insurance_date', 'Health insurance date'),
			text('work_email', 'Work email'),
			text('bank_account_name', 'Bank account name'),
			text('account_no', 'Account number'),
			text('bank', 'Bank'),
			text('branch', 'Branch'),
			text('ifsc', 'IFSC'),
		],
	},

	{
		key: 'job-profile',
		label: 'Job Profile',
		endpoint: '/api/v1/job-profile/',
		fields: [
			longText('job_description', 'Job description'),
		],
	},

	{
		key: 'on-employment',
		label: 'On Employment',
		endpoint: '/api/v1/on-employment/',
		fields: [
			number('employee_refno_id', 'Employee reference ID', true),
			text('employee_code', 'Employee code'),
			text('designation', 'Designation'),
			text('department', 'Department'),
			text('immediate_reporting_head', 'Immediate reporting head'),
			text('department_head', 'Department head'),
			text('epf_uan', 'EPF UAN'),
			text('esi', 'ESI'),
			text('health_insurance', 'Health insurance'),
			date('health_insurance_date', 'Health insurance date'),
			text('work_email', 'Work email'),
			text('bank_account_name', 'Bank account name'),
			text('account_no', 'Account number'),
			text('bank', 'Bank'),
			text('branch', 'Branch'),
			text('ifsc', 'IFSC'),
			number('salary_offered_ctc', 'Salary offered CTC'),
			number('yearly_increment', 'Yearly increment'),
			number('increment_year', 'Increment year'),
			number('basic', 'Basic'),
			number('allowance1', 'Allowance 1'),
			number('allowance2', 'Allowance 2'),
			number('allowance3', 'Allowance 3'),
			number('allowance4', 'Allowance 4'),
			number('allowance5', 'Allowance 5'),
			number('allowance6', 'Allowance 6'),
			number('other_allowance', 'Other allowance'),
			number('arrears', 'Arrears'),
			number('gross', 'Gross'),
			number('epf_deduction', 'EPF deduction'),
			number('esi_insurance_deduction', 'ESI insurance deduction'),
			number('tds', 'TDS'),
			number('canteen_deduction', 'Canteen deduction'),
			number('advance_deduction', 'Advance deduction'),
			number('loan_emi', 'Loan EMI'),
			number('other_deduction', 'Other deduction'),
			number('total_deductions', 'Total deductions'),
			number('net_salary', 'Net salary'),
			number('epf_employer_share', 'EPF employer share'),
			number('esi_employer_share', 'ESI employer share'),
			number('insurance_employer_share', 'Insurance employer share'),
			number('transport_allowance', 'Transport allowance'),
			number('canteen_allowance', 'Canteen allowance'),
			number('bonus', 'Bonus'),
			number('other_employer_contribution', 'Other employer contribution'),
			number('total_ctc', 'Total CTC'),
		],
	},

	{
		key: 'salary-details',
		label: 'Salary Details',
		endpoint: '/api/v1/salary-details/',
		fields: [
			number('user_id', 'User ID', true),
			date('effective_date', 'Effective Date'),
			number('salary_offered_ctc', 'Salary offered CTC'),
			number('yearly_increment', 'Yearly increment'),
			number('increment_year', 'Increment year'),
			number('basic', 'Basic'),
			number('allowance1', 'Allowance 1'),
			number('allowance2', 'Allowance 2'),
			number('allowance3', 'Allowance 3'),
			number('allowance4', 'Allowance 4'),
			number('allowance5', 'Allowance 5'),
			number('allowance6', 'Allowance 6'),
			number('other_allowance', 'Other allowance'),
			number('arrears', 'Arrears'),
			number('gross', 'Gross'),
			number('epf_deduction', 'EPF deduction'),
			number('esi_insurance_deduction', 'ESI insurance deduction'),
			number('tds', 'TDS'),
			number('canteen_deduction', 'Canteen deduction'),
			number('advance_deduction', 'Advance deduction'),
			number('loan_emi', 'Loan EMI'),
			number('other_deduction', 'Other deduction'),
			number('total_deductions', 'Total deductions'),
			number('net_salary', 'Net salary'),
			number('epf_employer_share', 'EPF employer share'),
			number('esi_employer_share', 'ESI employer share'),
			number('insurance_employer_share', 'Insurance employer share'),
			number('transport_allowance', 'Transport allowance'),
			number('canteen_allowance', 'Canteen allowance'),
			number('bonus', 'Bonus'),
			number('other_employer_contribution', 'Other employer contribution'),
			number('total_ctc', 'Total CTC'),
		],
	},

	{
		key: 'travelling-advance',
		label: 'Travelling Advance',
		endpoint: '/api/v1/travelling-advance/',
		fields: [
			number('user_id', 'User ID', true),
			text('employee_code', 'Employee code'),
			text('designation', 'Designation'),
			text('department', 'Department'),
			date('from_date', 'From date'),
			date('to_date', 'To date'),
			text('place_visited', 'Place visited'),
			longText('purpose_of_visit', 'Purpose of visit'),
			text('type_of_expense', 'Type of expense'),
			number('expense_amount', 'Expense amount'),
			text('additional_expense_type', 'Additional expense type'),
			number('additional_expense_amount', 'Additional expense amount'),
			text('other_expense_type', 'Other expense type'),
			number('other_expense_amount', 'Other expense amount'),
			number('total_advance', 'Total advance'),
		],
	},

	{
		key: 'travelling-expenses-reimbursement',
		label: 'Travelling Expenses Reimbursement',
		endpoint: '/api/v1/travelling-expenses-reimbursement/',
		fields: [
			number('user_id', 'User ID', true),
			text('name', 'Name'),
			text('employee_code', 'Employee code'),
			text('designation', 'Designation'),
			text('department', 'Department'),
			date('from_date', 'From date'),
			date('to_date', 'To date'),
			text('place_visited', 'Place visited'),
			longText('purpose_of_visit', 'Purpose of visit'),
			text('expense_type1', 'Expense type 1'),
			number('expense_amount1', 'Expense amount 1'),
			text('attachment1', 'Attachment 1'),
			text('expense_type2', 'Expense type 2'),
			number('expense_amount2', 'Expense amount 2'),
			text('attachment2', 'Attachment 2'),
			text('other_expense_type', 'Other expense type'),
			number('other_expense_amount', 'Other expense amount'),
			text('attachment3', 'Attachment 3'),
			number('total_amount', 'Total amount'),
		],
	},
]

export const adminResourceMap = Object.fromEntries(
	adminResources.map((resource) => [resource.key, resource]),
) as Record<string, AdminResource>